version: "3.9"

services:

  hello:
    image: hello-world

  cowsay:
    image: xshell/cowsay
    command: ['cowsay', 'wooooooooow']

  whalesay:
    image: docker/whalesay
    command: ['cowsay', 'weeeeeeeeee']

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    #volumes:
    #  - './data/redis:/data'
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]


  database:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3307:3306"
    #volumes:
    #  - ./data/mariadb/mysql:/var/lib/mysql
    #  - ./data/mariadb/initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_USER=docker
      - MYSQL_DATABASE=docker