name: Publish image to Docker Hub

on:
  push:
    tags:
      - "*"

env:
  REPO_NAME: docker-http

jobs:
  publish:
    name: Publish image
    runs-on: ubuntu-latest
    environment: production

    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Checkout repo with submodules
      uses: actions/checkout@v4


    - name: Build, tag, and push image to Docker Hub
      id: build-image
      env:
        #IMAGE_TAG: ${{ github.ref_type }}-${{ github.ref_name }}
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        docker build -t $REPO_NAME:$IMAGE_TAG .
        docker push $REPO_NAME:$IMAGE_TAG
        
        docker tag $REPO_NAME:$IMAGE_TAG $REPO_NAME:latest
        docker push $REPO_NAME:latest
        
        echo "image=$REPO_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT
